import type { Block } from "./libro";

export const MODULO4: Block[] = [
  {"type": "sumario", "items": ["La diferencia entre pensar y sentir", "Meditación activa: reentrenar el cerebro fuera del cuerpo conocido", "Coherencia cardíaca y regulación del sistema nervioso", "Ejercicios base de la semana 1", "Cómo se integran los tres ejercicios en una sola práctica diaria"]},
  {"type": "h", "text": "La diferencia entre pensar y sentir"},
  {"type": "p", "text": "Hay una distinción que parece sutil pero que cambia por completo la forma de abordar el foco: una cosa es pensar en concentrarte, y otra muy distinta es que tu cuerpo esté efectivamente en un estado fisiológico compatible con la concentración. Podés decirte a vos mismo \"ahora me voy a enfocar\" con toda la intención del mundo, pero si tu sistema nervioso está en un estado de activación de estrés (el que en fisiología se llama predominio simpático), la mente va a seguir saltando de un estímulo a otro por más que lo decidas conscientemente."},
  {"type": "p", "text": "Esta es la premisa central que este libro interactivo toma del trabajo de Joe Dispenza: el pensamiento por sí solo rara vez cambia un patrón, porque el patrón no vive únicamente en la mente, vive también en el cuerpo, en forma de tensión muscular, ritmo respiratorio, ritmo cardíaco y niveles de activación del sistema nervioso autónomo. Por eso el primer paso del método no es \"pensar mejor\", es cambiar el estado corporal para que el pensamiento enfocado tenga un terreno fisiológico donde sostenerse."},
  {"type": "ejemplo", "text": "Pensá en la diferencia entre sentarte a trabajar después de haber discutido con alguien, con el corazón acelerado y la mandíbula tensa, versus sentarte después de cinco minutos de respiración pausada. El contenido de la tarea es exactamente el mismo, pero la capacidad real de sostener la atención cambia radicalmente entre un estado y el otro. Eso no es una cuestión de actitud, es fisiología medible."},
  {"type": "h", "text": "Meditación activa: reentrenar el cerebro fuera del cuerpo conocido"},
  {"type": "p", "text": "Dispenza usa la expresión \"meditación activa\" para referirse a un tipo de práctica que no busca solamente relajación, sino un cambio deliberado de estado, saliendo del patrón corporal y emocional habitual (lo que él llama \"el cuerpo conocido\", el conjunto de sensaciones y tensiones que asociamos con nuestra identidad de todos los días). La idea de fondo, que sí tiene correlato en la literatura científica sobre meditación y atención, es que un estado de mayor calma fisiológica y menor reactividad emocional crea las condiciones necesarias para que la atención dirigida se sostenga con menos esfuerzo."},
  {"type": "p", "text": "Es importante ser precisos acá: la meditación activa, tal como la propone Dispenza, incluye elementos (visualización de un \"yo futuro\", trabajo con la glándula pineal, referencias a la física cuántica aplicada a la conciencia) que exceden lo que la ciencia puede confirmar con el mismo rigor que, por ejemplo, la investigación sobre respiración y sistema nervioso autónomo. Este libro interactivo toma de esa práctica lo que sí está bien respaldado: la combinación de respiración consciente, relajación corporal progresiva y visualización dirigida como herramienta para cambiar el estado de activación del sistema nervioso, sin extender esas conclusiones a terrenos que la evidencia actual no sostiene con el mismo nivel de certeza."},
  {"type": "h", "text": "Coherencia cardíaca y regulación del sistema nervioso"},
  {"type": "p", "text": "Acá hay uno de los puntos con mayor respaldo científico de todo el módulo. La variabilidad de la frecuencia cardíaca (HRV, por sus siglas en inglés) es una medida de cuánto varía el intervalo entre latidos, y refleja qué tan bien tu sistema nervioso autónomo se está adaptando en tiempo real. Una HRV más alta y ordenada se asocia con mayor flexibilidad del sistema nervioso, mientras que una HRV baja y desordenada se asocia con estrés, fatiga y desregulación emocional."},
  {"type": "p", "text": "La investigación sobre respiración lenta y pautada muestra algo muy concreto: cuando respirás a un ritmo de aproximadamente seis respiraciones por minuto (unos cinco segundos de inhalación y cinco de exhalación), el sistema respiratorio y el sistema cardiovascular entran en sincronía con la frecuencia natural de un reflejo llamado barorreflejo. A ese estado se lo llama coherencia cardíaca o coherencia cardiorrespiratoria, y está asociado en distintos estudios con mejoras en la regulación emocional, la claridad cognitiva y la capacidad de concentración."},
  {"type": "ejemplo", "text": "Contá mentalmente \"inhalo, dos, tres, cuatro, cinco\" mientras inhalás por la nariz, y \"exhalo, dos, tres, cuatro, cinco\" mientras soltás el aire de forma pausada por la boca.", "extra": "Sostené este ritmo durante tres a cinco minutos antes de cualquier tarea que requiera concentración sostenida. Esta es una herramienta que podés usar en cualquier lugar: antes de una reunión importante, antes de sentarte a escribir, o en medio de un pico de ansiedad que amenaza con hacerte perder el foco."},
  {"type": "h", "text": "Ejercicios base de la semana 1"},
  {"type": "p", "text": "Estos son los tres ejercicios que vas a alternar durante la primera semana del reto (los vas a encontrar detallados día por día en la Parte III). Acá te explico la lógica de cada uno."},
  {"type": "pasos", "items": [{"title": "Escaneo corporal", "paragraphs": ["Consiste en recorrer mentalmente el cuerpo de la cabeza a los pies, prestando atención a la tensión acumulada en cada zona sin intentar cambiarla, solo notándola. Este ejercicio entrena algo que en neurociencia se llama interocepción, la capacidad de percibir señales internas del propio cuerpo, y que está directamente relacionada con la capacidad de autorregulación emocional. Cuanto más precisa es tu percepción interoceptiva, más rápido podés detectar que estás entrando en un estado de activación que va a sabotear tu foco, antes de que ese estado tome el control."]}, {"title": "Respiración consciente (coherencia cardíaca)", "paragraphs": ["Como se explicó arriba, la respiración pautada a un ritmo de resonancia (aproximadamente seis ciclos por minuto) es la herramienta más directa y con mayor respaldo científico de este módulo para cambiar el estado del sistema nervioso en minutos."]}, {"title": "Visualización dirigida", "paragraphs": ["Consiste en imaginar, con el mayor detalle sensorial posible, cómo se siente estar completamente enfocado en una tarea, qué postura tiene tu cuerpo, qué ritmo tiene tu respiración, qué ausencia de tensión hay en tu mandíbula y tus hombros.", "La investigación en neurociencia del deporte y la rehabilitación motora muestra que la visualización detallada activa circuitos motores y atencionales parcialmente superpuestos con los que se activan al realizar la acción real, lo cual la convierte en una herramienta legítima de entrenamiento, no solo en un ejercicio de \"pensamiento positivo\"."]}]},
  {"type": "ejemplo", "text": "Antes de empezar a trabajar, cerrá los ojos 60 segundos y visualizate a vos mismo ya concentrado: la espalda erguida, la mandíbula relajada, la respiración lenta, la mirada fija en la pantalla o el papel sin desviarse. No visualices el resultado final del trabajo, visualizate a vos mismo en el proceso de estar enfocado. Es una diferencia sutil pero importante: estás entrenando el estado, no fantaseando con el objetivo."},
  {"type": "h", "text": "Cómo se integran los tres ejercicios en una sola práctica diaria"},
  {"type": "p", "text": "La secuencia recomendada, y la que vas a seguir en el reto, es: primero el escaneo corporal breve (para tomar registro de tu estado de partida), después la respiración de coherencia cardíaca (para cambiar activamente ese estado), y por último la visualización dirigida (para \"cargar\" el estado nuevo con una intención concreta de foco)."},
  {"type": "p", "text": "Toda la secuencia lleva entre 8 y 12 minutos, y está pensada para hacerse inmediatamente antes de cualquier bloque de trabajo o estudio que requiera concentración sostenida, no como una práctica aislada de la mañana desconectada del resto del día."},
  {"type": "cierre", "items": ["El pensamiento consciente por sí solo rara vez cambia un patrón de distracción, porque ese patrón también vive en el cuerpo, en forma de tensión y activación del sistema nervioso.", "La respiración pautada a un ritmo de aproximadamente seis ciclos por minuto tiene respaldo científico sólido para mejorar la coherencia cardíaca y la regulación del sistema nervioso.", "El escaneo corporal, la respiración consciente y la visualización dirigida son las tres herramientas base que vas a combinar en una secuencia diaria de 8 a 12 minutos.", "Este libro interactivo toma del trabajo de Dispenza lo que tiene respaldo científico claro (regulación del sistema nervioso mediante respiración y meditación activa), sin extender esas conclusiones a afirmaciones sobre física cuántica o manifestación que exceden lo que la evidencia puede confirmar."], "ejercicio": "Antes de tu próximo bloque de trabajo, probá la secuencia completa: un minuto de escaneo corporal, tres minutos de respiración de coherencia cardíaca (5 segundos de inhalación, 5 de exhalación), y un minuto de visualización dirigida de vos mismo ya enfocado.", "ejercicioExtra": "Registrá, en una escala de 1 a 10, qué tan presente te sentiste durante los primeros diez minutos de trabajo después del ejercicio, comparado con un día en el que empezás a trabajar sin esta preparación."},
];
