/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as BienvenidaRouteImport } from './routes/bienvenida'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAutoevaluacionRouteImport } from './routes/_authenticated/autoevaluacion'
import { Route as AuthenticatedGlosarioRouteImport } from './routes/_authenticated/glosario'
import { Route as AuthenticatedGuionesRouteImport } from './routes/_authenticated/guiones'
import { Route as AuthenticatedKitEmergenciaRouteImport } from './routes/_authenticated/kit-emergencia'
import { Route as AuthenticatedMenuRouteImport } from './routes/_authenticated/menu'
import { Route as AuthenticatedRegistroDiarioRouteImport } from './routes/_authenticated/registro-diario'
import { Route as AuthenticatedTrackerRouteImport } from './routes/_authenticated/tracker'
import { Route as AuthenticatedIndiceIndexRouteImport } from './routes/_authenticated/indice.index'
import { Route as AuthenticatedIndiceSeccionRouteImport } from './routes/_authenticated/indice.$seccion'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const BienvenidaRoute = BienvenidaRouteImport.update({
  id: '/bienvenida',
  path: '/bienvenida',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutoevaluacionRoute =
  AuthenticatedAutoevaluacionRouteImport.update({
    id: '/autoevaluacion',
    path: '/autoevaluacion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGlosarioRoute = AuthenticatedGlosarioRouteImport.update({
  id: '/glosario',
  path: '/glosario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuionesRoute = AuthenticatedGuionesRouteImport.update({
  id: '/guiones',
  path: '/guiones',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKitEmergenciaRoute =
  AuthenticatedKitEmergenciaRouteImport.update({
    id: '/kit-emergencia',
    path: '/kit-emergencia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMenuRoute = AuthenticatedMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRegistroDiarioRoute =
  AuthenticatedRegistroDiarioRouteImport.update({
    id: '/registro-diario',
    path: '/registro-diario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrackerRoute = AuthenticatedTrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIndiceIndexRoute =
  AuthenticatedIndiceIndexRouteImport.update({
    id: '/indice/',
    path: '/indice/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIndiceSeccionRoute =
  AuthenticatedIndiceSeccionRouteImport.update({
    id: '/indice/$seccion',
    path: '/indice/$seccion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bienvenida': typeof BienvenidaRoute
  '/privacidad': typeof PrivacidadRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terminos': typeof TerminosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/autoevaluacion': typeof AuthenticatedAutoevaluacionRoute
  '/glosario': typeof AuthenticatedGlosarioRoute
  '/guiones': typeof AuthenticatedGuionesRoute
  '/kit-emergencia': typeof AuthenticatedKitEmergenciaRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/registro-diario': typeof AuthenticatedRegistroDiarioRoute
  '/tracker': typeof AuthenticatedTrackerRoute
  '/indice/$seccion': typeof AuthenticatedIndiceSeccionRoute
  '/indice/': typeof AuthenticatedIndiceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bienvenida': typeof BienvenidaRoute
  '/privacidad': typeof PrivacidadRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terminos': typeof TerminosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/autoevaluacion': typeof AuthenticatedAutoevaluacionRoute
  '/glosario': typeof AuthenticatedGlosarioRoute
  '/guiones': typeof AuthenticatedGuionesRoute
  '/kit-emergencia': typeof AuthenticatedKitEmergenciaRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/registro-diario': typeof AuthenticatedRegistroDiarioRoute
  '/tracker': typeof AuthenticatedTrackerRoute
  '/indice/$seccion': typeof AuthenticatedIndiceSeccionRoute
  '/indice': typeof AuthenticatedIndiceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/bienvenida': typeof BienvenidaRoute
  '/privacidad': typeof PrivacidadRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terminos': typeof TerminosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/autoevaluacion': typeof AuthenticatedAutoevaluacionRoute
  '/_authenticated/glosario': typeof AuthenticatedGlosarioRoute
  '/_authenticated/guiones': typeof AuthenticatedGuionesRoute
  '/_authenticated/kit-emergencia': typeof AuthenticatedKitEmergenciaRoute
  '/_authenticated/menu': typeof AuthenticatedMenuRoute
  '/_authenticated/registro-diario': typeof AuthenticatedRegistroDiarioRoute
  '/_authenticated/tracker': typeof AuthenticatedTrackerRoute
  '/_authenticated/indice/$seccion': typeof AuthenticatedIndiceSeccionRoute
  '/_authenticated/indice/': typeof AuthenticatedIndiceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bienvenida'
    | '/privacidad'
    | '/reset-password'
    | '/terminos'
    | '/admin'
    | '/autoevaluacion'
    | '/glosario'
    | '/guiones'
    | '/kit-emergencia'
    | '/menu'
    | '/registro-diario'
    | '/tracker'
    | '/indice/$seccion'
    | '/indice/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bienvenida'
    | '/privacidad'
    | '/reset-password'
    | '/terminos'
    | '/admin'
    | '/autoevaluacion'
    | '/glosario'
    | '/guiones'
    | '/kit-emergencia'
    | '/menu'
    | '/registro-diario'
    | '/tracker'
    | '/indice/$seccion'
    | '/indice'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/bienvenida'
    | '/privacidad'
    | '/reset-password'
    | '/terminos'
    | '/_authenticated/admin'
    | '/_authenticated/autoevaluacion'
    | '/_authenticated/glosario'
    | '/_authenticated/guiones'
    | '/_authenticated/kit-emergencia'
    | '/_authenticated/menu'
    | '/_authenticated/registro-diario'
    | '/_authenticated/tracker'
    | '/_authenticated/indice/$seccion'
    | '/_authenticated/indice/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  BienvenidaRoute: typeof BienvenidaRoute
  PrivacidadRoute: typeof PrivacidadRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TerminosRoute: typeof TerminosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bienvenida': {
      id: '/bienvenida'
      path: '/bienvenida'
      fullPath: '/bienvenida'
      preLoaderRoute: typeof BienvenidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/autoevaluacion': {
      id: '/_authenticated/autoevaluacion'
      path: '/autoevaluacion'
      fullPath: '/autoevaluacion'
      preLoaderRoute: typeof AuthenticatedAutoevaluacionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/glosario': {
      id: '/_authenticated/glosario'
      path: '/glosario'
      fullPath: '/glosario'
      preLoaderRoute: typeof AuthenticatedGlosarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guiones': {
      id: '/_authenticated/guiones'
      path: '/guiones'
      fullPath: '/guiones'
      preLoaderRoute: typeof AuthenticatedGuionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kit-emergencia': {
      id: '/_authenticated/kit-emergencia'
      path: '/kit-emergencia'
      fullPath: '/kit-emergencia'
      preLoaderRoute: typeof AuthenticatedKitEmergenciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menu': {
      id: '/_authenticated/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AuthenticatedMenuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/registro-diario': {
      id: '/_authenticated/registro-diario'
      path: '/registro-diario'
      fullPath: '/registro-diario'
      preLoaderRoute: typeof AuthenticatedRegistroDiarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tracker': {
      id: '/_authenticated/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof AuthenticatedTrackerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indice/': {
      id: '/_authenticated/indice/'
      path: '/indice'
      fullPath: '/indice/'
      preLoaderRoute: typeof AuthenticatedIndiceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indice/$seccion': {
      id: '/_authenticated/indice/$seccion'
      path: '/indice/$seccion'
      fullPath: '/indice/$seccion'
      preLoaderRoute: typeof AuthenticatedIndiceSeccionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAutoevaluacionRoute: typeof AuthenticatedAutoevaluacionRoute
  AuthenticatedGlosarioRoute: typeof AuthenticatedGlosarioRoute
  AuthenticatedGuionesRoute: typeof AuthenticatedGuionesRoute
  AuthenticatedKitEmergenciaRoute: typeof AuthenticatedKitEmergenciaRoute
  AuthenticatedMenuRoute: typeof AuthenticatedMenuRoute
  AuthenticatedRegistroDiarioRoute: typeof AuthenticatedRegistroDiarioRoute
  AuthenticatedTrackerRoute: typeof AuthenticatedTrackerRoute
  AuthenticatedIndiceSeccionRoute: typeof AuthenticatedIndiceSeccionRoute
  AuthenticatedIndiceIndexRoute: typeof AuthenticatedIndiceIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAutoevaluacionRoute: AuthenticatedAutoevaluacionRoute,
  AuthenticatedGlosarioRoute: AuthenticatedGlosarioRoute,
  AuthenticatedGuionesRoute: AuthenticatedGuionesRoute,
  AuthenticatedKitEmergenciaRoute: AuthenticatedKitEmergenciaRoute,
  AuthenticatedMenuRoute: AuthenticatedMenuRoute,
  AuthenticatedRegistroDiarioRoute: AuthenticatedRegistroDiarioRoute,
  AuthenticatedTrackerRoute: AuthenticatedTrackerRoute,
  AuthenticatedIndiceSeccionRoute: AuthenticatedIndiceSeccionRoute,
  AuthenticatedIndiceIndexRoute: AuthenticatedIndiceIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  BienvenidaRoute: BienvenidaRoute,
  PrivacidadRoute: PrivacidadRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TerminosRoute: TerminosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
