/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as BienvenidaRouteImport } from './routes/bienvenida'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAutoevaluacionRouteImport } from './routes/_authenticated/autoevaluacion'
import { Route as AuthenticatedBotonAntiDistraccionRouteImport } from './routes/_authenticated/boton-anti-distraccion'
import { Route as AuthenticatedGlosarioRouteImport } from './routes/_authenticated/glosario'
import { Route as AuthenticatedGuionesRouteImport } from './routes/_authenticated/guiones'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedKitEmergenciaRouteImport } from './routes/_authenticated/kit-emergencia'
import { Route as AuthenticatedMenuRouteImport } from './routes/_authenticated/menu'
import { Route as AuthenticatedRegistroDiarioRouteImport } from './routes/_authenticated/registro-diario'
import { Route as AuthenticatedTrackerRouteImport } from './routes/_authenticated/tracker'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedIndiceIndexRouteImport } from './routes/_authenticated/indice.index'
import { Route as AuthenticatedIndiceSeccionRouteImport } from './routes/_authenticated/indice.$seccion'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const BienvenidaRoute = BienvenidaRouteImport.update({
  id: '/bienvenida',
  path: '/bienvenida',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutoevaluacionRoute =
  AuthenticatedAutoevaluacionRouteImport.update({
    id: '/autoevaluacion',
    path: '/autoevaluacion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBotonAntiDistraccionRoute =
  AuthenticatedBotonAntiDistraccionRouteImport.update({
    id: '/boton-anti-distraccion',
    path: '/boton-anti-distraccion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGlosarioRoute = AuthenticatedGlosarioRouteImport.update({
  id: '/glosario',
  path: '/glosario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuionesRoute = AuthenticatedGuionesRouteImport.update({
  id: '/guiones',
  path: '/guiones',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKitEmergenciaRoute =
  AuthenticatedKitEmergenciaRouteImport.update({
    id: '/kit-emergencia',
    path: '/kit-emergencia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMenuRoute = AuthenticatedMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRegistroDiarioRoute =
  AuthenticatedRegistroDiarioRouteImport.update({
    id: '/registro-diario',
    path: '/registro-diario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrackerRoute = AuthenticatedTrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndiceIndexRoute =
  AuthenticatedIndiceIndexRouteImport.update({
    id: '/indice/',
    path: '/indice/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIndiceSeccionRoute =
  AuthenticatedIndiceSeccionRouteImport.update({
    id: '/indice/$seccion',
    path: '/indice/$seccion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bienvenida': typeof BienvenidaRoute
  '/mcp': typeof McpRoute
  '/privacidad': typeof PrivacidadRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terminos': typeof TerminosRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/autoevaluacion': typeof AuthenticatedAutoevaluacionRoute
  '/boton-anti-distraccion': typeof AuthenticatedBotonAntiDistraccionRoute
  '/glosario': typeof AuthenticatedGlosarioRoute
  '/guiones': typeof AuthenticatedGuionesRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/kit-emergencia': typeof AuthenticatedKitEmergenciaRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/registro-diario': typeof AuthenticatedRegistroDiarioRoute
  '/tracker': typeof AuthenticatedTrackerRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/indice/$seccion': typeof AuthenticatedIndiceSeccionRoute
  '/indice/': typeof AuthenticatedIndiceIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bienvenida': typeof BienvenidaRoute
  '/mcp': typeof McpRoute
  '/privacidad': typeof PrivacidadRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terminos': typeof TerminosRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/autoevaluacion': typeof AuthenticatedAutoevaluacionRoute
  '/boton-anti-distraccion': typeof AuthenticatedBotonAntiDistraccionRoute
  '/glosario': typeof AuthenticatedGlosarioRoute
  '/guiones': typeof AuthenticatedGuionesRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/kit-emergencia': typeof AuthenticatedKitEmergenciaRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/registro-diario': typeof AuthenticatedRegistroDiarioRoute
  '/tracker': typeof AuthenticatedTrackerRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/indice/$seccion': typeof AuthenticatedIndiceSeccionRoute
  '/indice': typeof AuthenticatedIndiceIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/bienvenida': typeof BienvenidaRoute
  '/mcp': typeof McpRoute
  '/privacidad': typeof PrivacidadRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terminos': typeof TerminosRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/autoevaluacion': typeof AuthenticatedAutoevaluacionRoute
  '/_authenticated/boton-anti-distraccion': typeof AuthenticatedBotonAntiDistraccionRoute
  '/_authenticated/glosario': typeof AuthenticatedGlosarioRoute
  '/_authenticated/guiones': typeof AuthenticatedGuionesRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/kit-emergencia': typeof AuthenticatedKitEmergenciaRoute
  '/_authenticated/menu': typeof AuthenticatedMenuRoute
  '/_authenticated/registro-diario': typeof AuthenticatedRegistroDiarioRoute
  '/_authenticated/tracker': typeof AuthenticatedTrackerRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/_authenticated/indice/$seccion': typeof AuthenticatedIndiceSeccionRoute
  '/_authenticated/indice/': typeof AuthenticatedIndiceIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bienvenida'
    | '/mcp'
    | '/privacidad'
    | '/reset-password'
    | '/terminos'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/autoevaluacion'
    | '/boton-anti-distraccion'
    | '/glosario'
    | '/guiones'
    | '/inicio'
    | '/kit-emergencia'
    | '/menu'
    | '/registro-diario'
    | '/tracker'
    | '/.lovable/oauth/consent'
    | '/indice/$seccion'
    | '/indice/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bienvenida'
    | '/mcp'
    | '/privacidad'
    | '/reset-password'
    | '/terminos'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/autoevaluacion'
    | '/boton-anti-distraccion'
    | '/glosario'
    | '/guiones'
    | '/inicio'
    | '/kit-emergencia'
    | '/menu'
    | '/registro-diario'
    | '/tracker'
    | '/.lovable/oauth/consent'
    | '/indice/$seccion'
    | '/indice'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/bienvenida'
    | '/mcp'
    | '/privacidad'
    | '/reset-password'
    | '/terminos'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/autoevaluacion'
    | '/_authenticated/boton-anti-distraccion'
    | '/_authenticated/glosario'
    | '/_authenticated/guiones'
    | '/_authenticated/inicio'
    | '/_authenticated/kit-emergencia'
    | '/_authenticated/menu'
    | '/_authenticated/registro-diario'
    | '/_authenticated/tracker'
    | '/.lovable/oauth/consent'
    | '/_authenticated/indice/$seccion'
    | '/_authenticated/indice/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  BienvenidaRoute: typeof BienvenidaRoute
  McpRoute: typeof McpRoute
  PrivacidadRoute: typeof PrivacidadRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TerminosRoute: typeof TerminosRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bienvenida': {
      id: '/bienvenida'
      path: '/bienvenida'
      fullPath: '/bienvenida'
      preLoaderRoute: typeof BienvenidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/autoevaluacion': {
      id: '/_authenticated/autoevaluacion'
      path: '/autoevaluacion'
      fullPath: '/autoevaluacion'
      preLoaderRoute: typeof AuthenticatedAutoevaluacionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boton-anti-distraccion': {
      id: '/_authenticated/boton-anti-distraccion'
      path: '/boton-anti-distraccion'
      fullPath: '/boton-anti-distraccion'
      preLoaderRoute: typeof AuthenticatedBotonAntiDistraccionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/glosario': {
      id: '/_authenticated/glosario'
      path: '/glosario'
      fullPath: '/glosario'
      preLoaderRoute: typeof AuthenticatedGlosarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guiones': {
      id: '/_authenticated/guiones'
      path: '/guiones'
      fullPath: '/guiones'
      preLoaderRoute: typeof AuthenticatedGuionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kit-emergencia': {
      id: '/_authenticated/kit-emergencia'
      path: '/kit-emergencia'
      fullPath: '/kit-emergencia'
      preLoaderRoute: typeof AuthenticatedKitEmergenciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menu': {
      id: '/_authenticated/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AuthenticatedMenuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/registro-diario': {
      id: '/_authenticated/registro-diario'
      path: '/registro-diario'
      fullPath: '/registro-diario'
      preLoaderRoute: typeof AuthenticatedRegistroDiarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tracker': {
      id: '/_authenticated/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof AuthenticatedTrackerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/indice/': {
      id: '/_authenticated/indice/'
      path: '/indice'
      fullPath: '/indice/'
      preLoaderRoute: typeof AuthenticatedIndiceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indice/$seccion': {
      id: '/_authenticated/indice/$seccion'
      path: '/indice/$seccion'
      fullPath: '/indice/$seccion'
      preLoaderRoute: typeof AuthenticatedIndiceSeccionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAutoevaluacionRoute: typeof AuthenticatedAutoevaluacionRoute
  AuthenticatedBotonAntiDistraccionRoute: typeof AuthenticatedBotonAntiDistraccionRoute
  AuthenticatedGlosarioRoute: typeof AuthenticatedGlosarioRoute
  AuthenticatedGuionesRoute: typeof AuthenticatedGuionesRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedKitEmergenciaRoute: typeof AuthenticatedKitEmergenciaRoute
  AuthenticatedMenuRoute: typeof AuthenticatedMenuRoute
  AuthenticatedRegistroDiarioRoute: typeof AuthenticatedRegistroDiarioRoute
  AuthenticatedTrackerRoute: typeof AuthenticatedTrackerRoute
  AuthenticatedIndiceSeccionRoute: typeof AuthenticatedIndiceSeccionRoute
  AuthenticatedIndiceIndexRoute: typeof AuthenticatedIndiceIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAutoevaluacionRoute: AuthenticatedAutoevaluacionRoute,
  AuthenticatedBotonAntiDistraccionRoute:
    AuthenticatedBotonAntiDistraccionRoute,
  AuthenticatedGlosarioRoute: AuthenticatedGlosarioRoute,
  AuthenticatedGuionesRoute: AuthenticatedGuionesRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedKitEmergenciaRoute: AuthenticatedKitEmergenciaRoute,
  AuthenticatedMenuRoute: AuthenticatedMenuRoute,
  AuthenticatedRegistroDiarioRoute: AuthenticatedRegistroDiarioRoute,
  AuthenticatedTrackerRoute: AuthenticatedTrackerRoute,
  AuthenticatedIndiceSeccionRoute: AuthenticatedIndiceSeccionRoute,
  AuthenticatedIndiceIndexRoute: AuthenticatedIndiceIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  BienvenidaRoute: BienvenidaRoute,
  McpRoute: McpRoute,
  PrivacidadRoute: PrivacidadRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TerminosRoute: TerminosRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
